name = "carovana"
main = "worker.js"
compatibility_date = "2026-08-01"

[[durable_objects.bindings]]
name = "PARTITA"
class_name = "Partita"

[[durable_objects.bindings]]
name = "ARCHIVIO"
class_name = "Archivio"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Partita", "Archivio"]
